spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_NAME
    username: USERNAME
    password: PASSWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
    defer-datasource-initialization: true
  sql:
    init:
        mode: always